name: arma-reforger

services:
  server:
    image: ghcr.io/thegamecracks/arma-reforger:latest
    platform: linux/amd64
    ports:
      - 2001:2001/udp
      - 17777:17777/udp
      - 19999:19999/udp
    volumes:
      - ./profile:/home/profile
      - ./reforger:/reforger
      - ./steamcmd:/steamcmd
    environment:
      SERVER_PUBLIC_ADDRESS: public-ip
      GAME_NAME: My Docker Reforger Server
